### PR TITLE
https and changed where authentication is shown

### PR DESCRIPTION
**Pull request by jatinbs**

### CODE REVIEW

**Comment by jatinbs** [comment]
@nakula Adding a note that mentions v3 is deprecated and along with it providing a link to the v3 docs. Is that ok or is it unnecessary?

**Comment by jatinbs** [comment]
Or should we add a change log?

**Comment by utsavkesharwani** [comment]
timeout - The max value was updated to 1800 sec sometime back. This also needs to be update.

**Comment by jatinbs** [comment]
@utsavkesharwani done.

**Pull request merged**
